source-file ~/.config/tmux/catppuccin-latte.tmux

set -g status-position top

# Pane splits
bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind q kill-pane

# Pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Pane resize
bind > resize-pane -R 10
bind < resize-pane -L 10
bind + resize-pane -D 10
bind _ resize-pane -U 10

# Equalize panes
bind = select-layout tiled

# Windows
bind c new-window -c "#{pane_current_path}"
bind n next-window
bind p previous-window
bind -r 1 select-window -t 1
bind -r 2 select-window -t 2
bind -r 3 select-window -t 3
bind -r 4 select-window -t 4
bind -r 5 select-window -t 5
bind -r 6 select-window -t 6
bind -r 7 select-window -t 7
bind -r 8 select-window -t 8
bind -r 9 select-window -t 9
bind x kill-pane
