latte_base="#eff1f5"
latte_text="#4c4f69"
latte_mauve="#8839ef"
latte_surface1="#ccd0da"
latte_subtext0="#6c6f85"

set -g set-clipboard on
set -g status-position top
set -g status-style bg=$latte_base,fg=$latte_text
set -g status-left-style bg=$latte_base,fg=$latte_mauve
set -g status-right-style bg=$latte_base,fg=$latte_text
set -g window-status-style bg=$latte_base,fg=$latte_subtext0
set -g window-status-current-style bg=$latte_base,fg=$latte_mauve
set -g window-status-current-format "#[bold]#I:#W"
set -g window-status-format "#I:#W"
set -g pane-border-style fg=$latte_surface1
set -g pane-active-border-style fg=$latte_mauve
set -g message-style bg=$latte_mauve,fg=$latte_base

set -g escape-time 0
set -g mouse on
set -g repeat-time 1000
set -g history-limit 10000

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# Pane splits
bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind q kill-pane

# Pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Pane resize
bind > resize-pane -R 10
bind < resize-pane -L 10
bind + resize-pane -D 10
bind _ resize-pane -U 10

# Equalize panes
bind = select-layout tiled

# Windows
bind c new-window -c "#{pane_current_path}"
bind n next-window
bind p previous-window
bind -r 1 select-window -t 1
bind -r 2 select-window -t 2
bind -r 3 select-window -t 3
bind -r 4 select-window -t 4
bind -r 5 select-window -t 5
bind -r 6 select-window -t 6
bind -r 7 select-window -t 7
bind -r 8 select-window -t 8
bind -r 9 select-window -t 9
bind x kill-pane
